version: '3.8'

volumes:
  navilos-ubuntu: {}

services:
  navilos:
    build: .
    volumes:
      - ./navilos/:/navilos-app/
    container_name: navilos-container-0.2
    tty: true
#    command:
#      - bash
#      - -c
#      - |
#        arm-none-eabi-gcc -v
#    restart: always
